name: hhcom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.2.4
  sizer: ^2.0.13
  google_fonts: ^2.1.0
  intl: ^0.17.0
  country_code_picker: ^2.0.2
  flutter_calendar_carousel: ^2.0.3
  date_time_picker: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  bottom_picker: ^1.0.6
  awesome_dropdown: ^0.0.4
  clay_containers: ^0.3.2
  flutter_neumorphic: ^3.2.0
  menu_button: ^1.4.2+1
  simple_shadow: ^0.2.0
  dropdown_below: ^1.0.1
  collection: any
  fialogs: ^2.0.4






  bloc:
  flutter_bloc:
  equatable:

  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_database:
  firebase_storage:

  page_transition:
  shared_preferences:
  fluttertoast:
  flutter_svg:
  image_picker:
  permission_handler:
  cached_network_image:
  dio:
  json_annotation: ^4.3.0
  another_flushbar:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

